print("\nTHANK YOU FOR YOUR PURCHASE, HERE ARE YOUR TRANSACTION DETAILS")
print("Customer Name:", customer.name)
print("Customer Age:", customer.age)
print("Product Name:", product.prodname)
print("Product Price:", price)
print("Product Quantity:", quantity)
print("Total Sales:", total)
print("Discount:", discount)
print("Net Cost:", net)
print("Amount Paid:", amount)
print("Change:", change)